import app from 'flarum/admin/app';

const EXTENSION_ID = 'stalir-mc-bridge';

app.initializers.add(EXTENSION_ID, () => {
  // The shared secret is deliberately not editable here: it is generated by
  // `php flarum mc-bridge:secret` and shown only in the console.
  app.extensionData
    .for(EXTENSION_ID)
    .registerSetting({
      setting: 'mc-bridge.locale',
      type: 'select',
      options: {
        'zh-Hans': app.translator.trans(`${EXTENSION_ID}.admin.settings.locale_zh`),
        en: app.translator.trans(`${EXTENSION_ID}.admin.settings.locale_en`),
      },
      label: app.translator.trans(`${EXTENSION_ID}.admin.settings.locale_label`),
      help: app.translator.trans(`${EXTENSION_ID}.admin.settings.locale_help`),
    })
    .registerSetting({
      setting: 'mc-bridge.announcement_tag_ids',
      type: 'text',
      label: app.translator.trans(`${EXTENSION_ID}.admin.settings.tags_label`),
      help: app.translator.trans(`${EXTENSION_ID}.admin.settings.tags_help`),
    })
    .registerSetting({
      setting: 'mc-bridge.sync_replies',
      type: 'checkbox',
      label: app.translator.trans(`${EXTENSION_ID}.admin.settings.sync_replies_label`),
      help: app.translator.trans(`${EXTENSION_ID}.admin.settings.sync_replies_help`),
    });
});
